### ISSUE TITLE
bug: stat values overlapping with labels

### ISSUE THREAD

**Issue by NotYourAverageGamer** [Ascension-Addons/AllStats#1]
### Description

The numbers are partially overlapping many of the stats for `Melee`, `Ranged` and `Spell`, making it very difficult to read
`Crit Chance` and `Bonus Damage` also have major issues with their formatting.

I have tried making changes to the AllStats addon, however I believe this may be an upstream (Ascension) issue?
It looks like the character frame has been slimmed at some point, including the Stats frame, which has led to AllStats also becoming thinner

Maybe we can add the labels and values separately, so that AllStats can be easier to customise for end users if something like this arises in future

***Edit:*** decided to check Elune and it appears to me that the overlapping isnt as big of an issue there? though, my character there still has low stats, so its a bit hard for me to tell. it definitely looks wider to me though. (the background width was done by me in troubleshooting)

elune does however have the issue with spell bonus damage and crit chance pop out frames

### Realm

Area 52 (Default)

### Tested with only this addon

- [X] Yes
- [ ] No

### Lua Error

this is not causing any errors to pop up

### Reproduction Steps

- download latest version of AllStats from the Addons section of the launcher
- login
- press `C` to open character frame
- see overlap in AllStats frame

### Last Good Version

Janurary 7th 2024

### Screenshots

here is the link to the comment in szylers discord of the most recent photo of this addon working as intended, that i could find https://discord.com/channels/713373289451618346/1060345865459474442/1193502288245960764

working pic: 
![allstats](https://github.com/user-attachments/assets/e93fac37-4eb6-4d1f-b685-5bc3c6280b1e)

Comparison of Elune and A52 (elune spacing is good? Ignore background width, that was me)
![Comparison](https://github.com/user-attachments/assets/f516fdd8-3272-45af-a125-f02ba934bae4)

**Comment by NotYourAverageGamer** [comment]
Updated original post with new screenshots and a bit more of a description after checking results on Elune

@andrew6180

**Comment by NotYourAverageGamer** [comment]
![Untitled](https://github.com/user-attachments/assets/f516fdd8-3272-45af-a125-f02ba934bae4)

**Comment by andrew6180** [comment]
@NotYourAverageGamer you have another addon changing font sizes globally on a52. AllStats isn't designed to scale with a different font size. 

Will fix tooltip for spell stuff.

**Comment by andrew6180** [comment]
Cant actually reproduce tooltip issue either. Need lua errors to do anything about it since it seems to work fine.

**Comment by NotYourAverageGamer** [comment]
Ahh, you're right! it was ElvUI causing issues. Seemed to be a mix of Font choice and size
The setting (in ElvUI) that adjusts the font size for the AllStats window is under `General > Media > Font Size`.
Will play around with that until i find something better suited. Thanks a bunch for helping me find that!

Tooltip issue appears to be fixed, even with ElvUI enabled, i no longer see tooltips like that. (it wasnt actually producing lua errors either, at least not with bugsack and !bug grabber)
